name: main
on: [push]

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: dep
        run: brew install catch2

      - name: gen
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -- -j4
      
      - name: test
        run: cd build && ctest
